### ISSUE TITLE
Terrible results when retrained

### ISSUE THREAD

**Issue by gaborcsapo** [campdav/Text-Generation-using-Bidirectional-LSTM-and-Doc2Vec-models#1]
I forked and retrained you notebook on two english books twice, but the results turned out worse than the basic LSTM setup. I can’t read French, so can’t judge the performance of your training, but it seems definitely better than mine. You can take a look at my notebooks [here](https://github.com/gaborcsapo/Text-Generation-using-Bidirectional-LSTM-and-Doc2Vec-models).

**Comment by campdav** [comment]
Yes, indeed... Did you try to tune the temperature value ? It could change a lot.
I download your notebook and I try to run it.

**Comment by campdav** [comment]
I've downloaded your notebooks and the two texts you used from Gutenberg.
First, regarding your second model (notebook 2), there is something wrong on the dataset cleaning. I assume it comes from unicode format you are using. If you check the first sentence :
sentence 0 : [u’\r\n’, u’the’, u’trees’, u’of’, u’pride’, u’\r\n\r\n’, u’by’, u’gilbert’, u’k.’, u’chesterton’, u’\r\n\r\n\r\n\r\n\r\n’, u’the’, u’trees’, u’of’, u’pride’, u’:’]
You have bad letters, that are understood as words (u’\r\n’, u’\r\n\r\n’,etc.) . Indeed, they are carriage returns at the end of the lines in your initial texts : it works as if you had random blank words in your sentence, and I assumes it has bad impact on you model. Maybe because you run python 2.7 when I used python 3, so you have also to update the cleaning in the create_sentences() functions (notebook 1 and 2).
As a test, using your data, I cleaned them, train a quick simple doc2vec (only 50 dimensions) and retrain the LSTM: it ends with an accuracy third time better.
To end  the test, I train also a simple LSTM with small RNN size (64) for the notebook 1, using your dataset. As expected, the output is worst than yours because of the weak training, but the combination of both seems to improve the whole. 
In all case, the first model is key, and the better it is, the better will we the whole thing. I assume there is plenty of room to improve this one, maybe using others methods that LSTM, adding embedding layers, etc.
Hoping it helps,

**Comment by gaborcsapo** [comment]
Merci beaucoup! It is indeed very helpful! I'll try again with python 3 and I'll make sure to clean carriage returns from the data. I chose those two books at random. I'll let you know how is the end result.

My final project is part of a student publication and will be trained on 200 academic essays, each about 600 words. BTW, great project, thanks for writing the Medium article, very informative!
